# Generated by Django 5.0.6 on 2024-07-03 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('pedido_id', models.AutoField(primary_key=True, serialize=False)),
                ('cliente', models.CharField(max_length=100)),
                ('fecha_pedido', models.DateTimeField(auto_now_add=True)),
                ('total_pedido', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('producto_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80)),
                ('email', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
                ('apellido_paterno', models.CharField(max_length=30)),
                ('apellido_materno', models.CharField(max_length=30)),
                ('telefono', models.CharField(max_length=12)),
                ('password', models.CharField(max_length=30)),
                ('direccion', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
