# Generated by Django 5.0.6 on 2024-07-03 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZonaGamers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarritoJuego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ZonaGamers.carrito')),
            ],
        ),
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('precio', models.DecimalField(decimal_places=0, max_digits=10)),
                ('descripcion', models.TextField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
        migrations.AddField(
            model_name='carritojuego',
            name='juego',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ZonaGamers.juego'),
        ),
        migrations.AlterUniqueTogether(
            name='carritojuego',
            unique_together={('carrito', 'juego')},
        ),
    ]
