# Generated by Django 5.0.6 on 2024-07-03 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZonaGamers', '0002_carrito_carritojuego_juego_delete_producto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carritojuego',
            name='cantidad',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
