# Generated by Django 5.0.6 on 2024-07-04 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZonaGamers', '0003_alter_carritojuego_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juego',
            name='precio',
            field=models.PositiveBigIntegerField(),
        ),
    ]
