# Generated by Django 5.0.6 on 2024-10-13 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZonaGamers', '0006_carrito_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='juego',
            name='codigo',
            field=models.CharField(default='sin_codigo', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
